apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 20.6.0
appVersion: v2.9.5
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - üîçÔ∏è Add filePath support on access logs
    - :bug: Add missing scheme in help on Traefik Hub integration (#746)
    - :memo: Improve documentation on using PVC with TLS certificates
