apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 22.2.0
# renovate: image=traefik
appVersion: v2.10.0
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "chore: ğŸ”§ new release"
    - "added targetPort support"
    - "fix: ğŸ› annotations leaking between aliased subcharts"
    - "fix: indentation on `TLSOption`"
    - "test: ğŸ‘· Update unit tests tooling"
    - "feat: override container port"
    - "feat: allow to set dnsConfig on pod template"
