apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 37.3.0
# renovate: image=traefik
appVersion: v3.6.0
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "tests: update certificatesResolvers with Proxy v3.6 options"
    - "fix: add missing flag arg"
    - "fix(doc): :books: comment grammar in values.yaml"
    - "feat: knative provider"
    - "feat(deps): update traefik docker tag to v3.6.0"
    - "feat(deps): update traefik docker tag to v3.5.4"
    - "feat(CRDs): update for Traefik Proxy v3.6 and Gateway API v1.4.0"
    - "feat(CRDs): update Traefik Hub to v1.23.1"
    - "docs: ðŸ“š fix comment grammar in values"
    - "chore(release): ðŸš€ publish traefik 37.3.0 and 1.12.0"
