apiVersion: v1
name: traefik
version: 8.9.0
appVersion: 2.2.1
description: A Traefik based Kubernetes ingress controller
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/containous/traefik
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ludovic@containo.us
engine: gotpl
icon: https://raw.githubusercontent.com/containous/traefik/v2.2/docs/content/assets/img/traefik.logo.png
