apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 36.1.0
# renovate: image=traefik
appVersion: v3.4.1
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix(schema): ğŸ› allow additional properties on `global`"
    - "fix(chart): update icon link to track upstream master branch"
    - "fix(Traefik Hub): add strict check on admission cert"
    - "feat(Traefik Hub): add v3.17 version mapping"
    - "chore(release): ğŸš€ publish v36.1.0"
