apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 23.1.0
# renovate: image=traefik
appVersion: v2.10.3
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "release: ğŸš€ publish v23.1.0"
    - "feat: âœ¨ add a warning when labelSelector don't match"
    - "feat: add optional `appProtocol` field on Service ports"
    - "feat: â– remove Traefik Hub v1 integration"
    - "feat: allow specifying service loadBalancerClass"
    - "feat: common labels for all resources"
    - "fix: ğŸ› use k8s version for hpa api version"
    - "fix: ğŸ› http3 support on traefik v3"
    - "fix: use `targetPort` instead of `port` on ServiceMonitor"
    - "doc: added values README via helm-docs cli"
