apiVersion: v2
name: traefik
version: 8.10.0
appVersion: 2.2.8
description: A Traefik based Kubernetes ingress controller
type: application
version: 9.1.0
appVersion: 2.2.8
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/containous/traefik
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ludovic@containo.us
icon: https://raw.githubusercontent.com/containous/traefik/v2.2/docs/content/assets/img/traefik.logo.png
