apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 25.0.0
# renovate: image=traefik
appVersion: 2.10.6
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "feat: âœ¨ add healthcheck ingressRoute"
    - "feat: :boom: support http redirections and http challenges with cert-manager"
    - "feat: :boom: rework and allow update of namespace policy for Gateway"
    - "fix: disable ClusterRole and ClusterRoleBinding when not needed"
    - "fix: detect correctly v3 version when using sha in `image.tag`"
    - "fix: allow updateStrategy.rollingUpdate.maxUnavailable to be passed in as an int or string"
    - "fix: add missing separator in crds"
    - "fix: add Prometheus scraping annotations only if serviceMonitor not created"
    - "docs: Fix typo in the default values file"
    - "chore: remove label whitespace at TLSOption"
    - "chore(release): ðŸš€ publish v25.0.0"
    - "chore(deps): update traefik docker tag to v2.10.5"
    - "chore(deps): update docker.io/helmunittest/helm-unittest docker tag to v3.12.3"
    - "chore(ci): ðŸ”§ ðŸ‘· add e2e test when releasing"
