apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 38.0.1
# renovate: image=traefik
appVersion: v3.6.5
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix(ports): ğŸ› add missing `http.maxHeaderBytes` option"
    - "fix(ports): ğŸ› `http.encodedCharacters` on custom entrypoints"
    - "chore(release): ğŸš€ publish traefik 38.0.1"
