apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 39.0.1
# renovate: image=traefik
appVersion: v3.6.8
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "tests(hub): relocate and clean api gw tests"
    - "fix(grpc): enforce mutually exclusive TLS and insecure options"
    - "fix(chart): allow to be used as optional subchart"
    - "fix(chart): add nameOverride and fullnameOverride to schema file"
    - "fix(api): add support for missing insecure and debug options"
    - "feat(deps): update traefik docker tag to v3.6.8"
    - "feat(deployment): support templating for podLabels"
    - "docs(schema): add description from helm-docs comments"
    - "chore(release): publish v39.0.1"
