apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 39.0.0
# renovate: image=traefik
appVersion: v3.6.7
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "refactor(chart): clean output on Deployment & Daemonset"
    - "fix(security)!: add support for request path options of Traefik 3.6.7+"
    - "fix(ports)!: ğŸ› entrypoints `http` options"
    - "feat(gateway-api): add support for defaultScope experimental feature"
    - "feat(deps)!: update traefik docker tag to v3.6.7"
    - "feat(chart): enforce schema"
    - "feat(CRDs)!: support Traefik Hub v3.19.0"
    - "docs(values): avoid unbreakable lines in table output of VALUES.md"
    - "chore(release): ğŸš€ publish traefik 39.0.0 and crds 1.14.0"
