apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 21.0.0
# renovate: image=traefik
appVersion: v2.9.7
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "ğŸ’¥ New release with BREAKING changes"
    - "Configure Renovate (#783)"
    - ":bug: Disabling dashboard ingressroute should delete it (#785)"
    - ":boom: Rename image.name => image.repository (#784)"
    - ":necktie: Improve labels settings behavior on metrics providers (#774)"
    - "âœ¨ Chart.yaml - add kubeVersion: ">=1.16.0-0""
    - "fix: allowExternalNameServices for kubernetes ingress when hub enabled (#772)"
    - "ğŸ™ˆ Add a setting disable API check on Prometheus Operator (#769)"
    - "ğŸ“ Improve documentation on entrypoint options"
    - "fix(service-metrics): invert prometheus svc & fullname length checking"
