apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 38.0.0
# renovate: image=traefik
appVersion: v3.6.5
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "fix: update error message for maxUnavailable validation"
    - "fix(pvc): allow empty storageClassName"
    - "fix(providers)!: align labelSelector for kubernetesGateway and knative"
    - "fix(notes): minor typo"
    - "fix(nginx)!: ğŸ› align provider settings and provide required rbac"
    - "feat(security): âœ¨ ğŸ”’ï¸ add support for request path options of traefik 3.6.4+"
    - "feat(providers): âœ¨ enforce schema"
    - "feat(ports): enforce schema"
    - "feat(deps): update traefik docker tag to v3.6.5"
    - "feat(deps): update traefik docker tag to v3.6.4"
    - "feat(CRDs): update Traefik Hub to v1.24.2"
    - "feat(CRDs): update Traefik Hub to v1.24.1, with required RBACs"
    - "chore(release): ğŸš€ publish traefik 38.0.0 and crds 1.13.0"
