apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 24.0.1
# renovate: image=traefik
appVersion: v2.10.5
kubeVersion: ">=1.16.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/traefik/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ldez@traefik.io
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: charlie-haley
    email: charlie.haley@traefik.io
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "chore(release): ðŸš€ publish v24.0.0"
    - "fix: http3 support broken when advertisedPort set"
    - "fix: tracing.opentelemetry.tls is optional for all values"
    - "chore(deps): update docker.io/helmunittest/helm-unittest docker tag to v3.12.2"
    - "chore(tests): ðŸ”§ fix typo on tracing test"
    - "fix: ðŸ’¥ BREAKING CHANGE on healthchecks and traefik port"
    - "feat: multi namespace RBAC manifests"
