apiVersion: v2
name: traefik-crds
description: A Traefik based Kubernetes ingress controller
type: application
version: 1.14.0
kubeVersion: ">=1.22.0-0"
keywords:
  - traefik
  - ingress
  - networking
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik-helm-chart
  - https://github.com/traefik/traefik
maintainers:
  - name: mloiseleur
    email: michel.loiseleur@traefik.io
  - name: darkweaver87
    email: remi.buisson@traefik.io
  - name: jnoordsij
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - "feat(CRDs)!: support Traefik Hub v3.19.0"
    - "docs(CRDs): improve note on deprecation"
    - "chore(release): ðŸš€ publish traefik 39.0.0 and crds 1.14.0"
