# Default values for Traefik CRDs
# This is a YAML-formatted file.
# Declare variables to be passed into templates

# -- Global values
# This definition is only here as a placeholder such that it is included in the json schema.
global: {}  # @schema additionalProperties: true
# -- Field that can be used as a condition when this chart is a dependency.
# This definition is only here as a placeholder such that it is included in the json schema.
# See https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags for more info.
enabled: true
# -- Install Traefik CRDs by default
traefik: true
# -- Set it to true to install GatewayAPI CRDs.
# Needed if you set providers.kubernetesGateway.enabled to true in main chart
# Cannot be used together with gatewayAPIExperimental
gatewayAPI: false
# -- Set it to true to install experimental GatewayAPI CRDs.
# This includes additional experimental features beyond the standard Gateway API
# Cannot be used together with gatewayAPI
gatewayAPIExperimental: false
# -- Set it to true to install Knative CRDs.
# Needed if you set providers.knative.enabled to true in main chart
knative: false
# -- Set it to true to install Traefik Hub CRDs.
# Needed if you set hub.enabled to true in main chart
hub: false
# -- Set it to true if you want to uninstall CRDs when uninstalling this chart.
# By default, CRDs will be kept so your custom resources will not be deleted accidentally.
deleteOnUninstall: false
