---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  # curl -o gateway-standard-install.yaml -L https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/standard-install.yaml
  - gateway-standard-install.yaml
  - hub.traefik.io_accesscontrolpolicies.yaml
  - hub.traefik.io_aiservices.yaml
  - hub.traefik.io_apiauths.yaml
  - hub.traefik.io_apibundles.yaml
  - hub.traefik.io_apicatalogitems.yaml
  - hub.traefik.io_apiplans.yaml
  - hub.traefik.io_apiportalauths.yaml
  - hub.traefik.io_apiportals.yaml
  - hub.traefik.io_apiratelimits.yaml
  - hub.traefik.io_apis.yaml
  - hub.traefik.io_apiversions.yaml
  - hub.traefik.io_managedapplications.yaml
  - hub.traefik.io_managedsubscriptions.yaml
  - traefik.io_ingressroutes.yaml
  - traefik.io_ingressroutetcps.yaml
  - traefik.io_ingressrouteudps.yaml
  - traefik.io_middlewares.yaml
  - traefik.io_middlewaretcps.yaml
  - traefik.io_serverstransports.yaml
  - traefik.io_serverstransporttcps.yaml
  - traefik.io_tlsoptions.yaml
  - traefik.io_tlsstores.yaml
  - traefik.io_traefikservices.yaml
