name: üßë‚Äçüî¨ E2E tests
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
  PLATFORM_URL: ${{ secrets.PLATFORM_URL }}
  ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
  EXTERNAL_TOKEN: ${{ secrets.EXTERNAL_TOKEN }}
  DOCKER_NON_INTERACTIVE: true
  LOG_LEVEL: info
jobs:
  run-walkthrough:
    runs-on: ubuntu-latest
    steps:
      - name: checkout traefik-helm-chart
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ${{ github.workspace }}/traefik-helm-chart
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: traefik/hub
          path: ${{ github.workspace }}/hub
      - name: set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: ${{ github.workspace }}/hub/tests/go.mod
          cache-dependency-path: ${{ github.workspace }}/hub/tests/go.sum
      - name: update tests
        run: |
          sed -i -r "s|\"traefik/traefik\"|\"${{ github.workspace }}/traefik-helm-chart/traefik/\"|g" ${{ github.workspace }}/hub/tests/*/*.go
      - name: run tests
        working-directory: ${{ github.workspace }}/hub/tests
        run: make test-walkthrough
